### PR TITLE
Upgrading to golang1.12 and pinning to specific version of prometheus

### PR DESCRIPTION
**Pull request by dcaba**
Time for an update?

* Suggesting to upgrade to golang 1.12.x
* Pinning to the latest prometheus version
  * to achieve that, I suggest to switch to go mod... 
  * however, as a side effect, the build now takes quite long, as go get with modules support do not honor vendored modules in prometheus (but the versions)
* Bringing a Makefile to drive the build/push
* And suggesting to align the tags with the prometheus version we are consuming
  * we can do smarter things, and maintain something like: latest + 2.9.2 + 2.9.2-commitID .. up to you!
* I also kept an extra CI example from the fork where I forked, https://github.com/ricardo-ch/docker-promtool

If you are happy with this, willing to see the new version in dockerhub ;)

### CODE REVIEW

**Comment by dcaba** [comment]
Hey @geekdave : is this interesting? If not, happy to publish the associated image in parallel / as a fork. Best!!

**Comment by geekdave** [comment]
@dcaba thanks so much!  Merging, and will publish a new image shortly.

**Comment by geekdave** [comment]
@dcaba published `dnanexus/promtool:2.9.2`.  See ~https://cloud.docker.com/u/dnanexus/repository/docker/dnanexus/promtool/tags~ https://hub.docker.com/r/dnanexus/promtool/tags EDIT: Fixed link

**Comment by dcaba** [comment]
Great! Thanks so much, @geekdave . Previous link may be wrong, though (I used this: https://hub.docker.com/r/dnanexus/promtool/tags ). Best wishes!

**Comment by geekdave** [comment]
@dcaba You're right -- your link is correct.  Thanks again for the contribution! 🎉

**Pull request merged**
